<PrintScreen>:
    BoxLayout:
        orientation: 'vertical'
        Image:
            id: im
            size_hint: 0.9, 0.9
            pos_hint: {'center_x': .5, 'center_y': .5}
            source: 'images/blank_9x9.png'
            allow_stretch: True
        Button:
            pos_hint: {'center_x': .5, 'center_y': .5}
            size_hint: None, 0.1
            width: min([im.width,im.height])
            text: 'Print'



